@baseUrl = http://localhost:8080
@projectId = 

@memberId = 

### 1. CREATE PROJECT
POST {{baseUrl}}/api/v1/projects
Content-Type: application/json

{
  "name": "",
  "description": ""
}

### 2. GET ALL PROJECTS
GET {{baseUrl}}/api/v1/projects

### 3. GET PROJECT BY ID
GET {{baseUrl}}/api/v1/projects/{{projectId}}

### 4. UPDATE PROJECT
PATCH {{baseUrl}}/api/v1/projects/{{projectId}}
Content-Type: application/json

{
  "name": "",
  "description": ""
}

### 5. DELETE PROJECT
DELETE {{baseUrl}}/api/v1/projects/{{projectId}}

### 6. GET PROJECT MEMBERS
GET {{baseUrl}}/api/v1/projects/{{projectId}}/members

### 7. ADD MEMBERS TO PROJECT
POST {{baseUrl}}/api/v1/projects/{{projectId}}/members
Content-Type: application/json

{
  "email": "",
  "role": ""
}

# Roles available: OWNER, ADMIN, MANAGER, MEMBER, VIEWER

### 8. UPDATE MEMBER ROLE
PATCH {{baseUrl}}/api/v1/projects/{{projectId}}/members/{{memberId}}/role
Content-Type: application/json

{
  "newRole": ""
}

# Roles available: OWNER, ADMIN, MANAGER, MEMBER, VIEWER

### 9. DELETE MEMBER 
DELETE {{baseUrl}}/api/v1/projects/{{projectId}}/members/{{memberId}}
