@baseUrl = http://localhost:8080

### 1. REGISTER USER
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "",
  "username": "",
  "fullName": "",
  "password": ""
}

### 2. LOGIN USER
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "",
  "password": ""
}

### 3. GET CURRENT USER
GET {{baseUrl}}/api/v1/auth/me

### 4. LOGOUT USER
POST {{baseUrl}}/api/v1/auth/logout

### 5. REFRESH ACCESS TOKEN
POST {{baseUrl}}/api/v1/auth/refresh-token
Content-Type: application/json

### 6. CHANGE CURRENT PASSWORD
PATCH {{baseUrl}}/api/v1/auth/me/change-password
Content-Type: application/json

{
  "oldPassword": "",
  "newPassword": ""
}

### 7. DELETE ACCOUNT
DELETE {{baseUrl}}/api/v1/auth/me
Content-Type: application/json

{
  "password": ""
}
