@baseUrl = http://localhost:8080

@taskId = 

@subTaskId = 

@projectId = 

@accessToken = 

############################################################
### TASKS
############################################################

### Create Task 
POST {{baseUrl}}/api/v1/tasks/projects/{{projectId}}/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "",
  "description": "",
  "assignedToId": "",
  "status": ""
}

# Status available: TODO, IN_PROGRESS, DONE

### Get All Tasks 
GET {{baseUrl}}/api/v1/tasks/projects/{{projectId}}/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Task by ID 
GET {{baseUrl}}/api/v1/tasks/{{projectId}}/tasks/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Update Task 
PATCH {{baseUrl}}/api/v1/tasks/{{projectId}}/tasks/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "description": ""
}

### Delete Task 
DELETE {{baseUrl}}/api/v1/tasks/{{projectId}}/tasks/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}


############################################################
### SUBTASKS
############################################################

### Create SubTask
POST {{baseUrl}}/api/v1/tasks/{{taskId}}/subtasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": ""
}

### Update SubTask
PATCH {{baseUrl}}/api/v1/tasks/{{taskId}}/subtasks/{{subTaskId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": ""
}

### Delete SubTask
DELETE {{baseUrl}}/api/v1/tasks/{{taskId}}/subtasks/{{subTaskId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
